apiVersion: v1
kind: Service
metadata:
  name: rustdesk-server
spec:
  selector:
    app: rustdesk-server
  ports:
  - protocol: TCP
    port: 21115 
    targetPort: 21115 
  type: LoadBalancer # Or NodePort depending on your cluster setup
